- name: Install PostgreSQL
  include_role:
    name: geerlingguy.postgresql
  vars:
    ansible_become: true
    postgresql_python_library: python3-psycopg2
    postgres_users_no_log: false
    postgresql_databases:
      - name: thenewboston
    postgresql_users:
      - name: thenewboston
        password: thenewboston
    postgresql_hba_entries:
      - {type: local, database: all, user: thenewboston, auth_method: trust}
      - {type: local, database: all, user: postgres, auth_method: trust}
      - {type: local, database: all, user: all, auth_method: peer}
      - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
      - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}