- name: Install Required Ubuntu Dependencies
  apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: true
  become: true
  vars:
    packages:
    - sudo
    - htop
    - git
    - nano
    - acl
    - build-essential
    - software-properties-common
    - libssl-dev 
    - python3.8
    - python3.8-dev 
    - python3-pip
    - libpq-dev

- name: Add the user 'tnb'
  user:
    name: tnb
    groups: "sudo,admin"
    comment: User for the new boston servers
